-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgCScl4R9H7cANVjbR
 vYl4l9w6iSIZT7bebr/ePLt4IM6gCgYIKoZIzj0DAQehRANCAATNOzOnJpM+JmS
 + xdXqZO+nSJv6OhIbN/OwXOWQWRV/Khw7gRG4SNOIxYyl2LKHrcdgIq8aLUIG6
 r oX iPnYVXKN
-----END PRIVATE KEY-----